version: '3.9'

services:
 # ========== RABBITMQ (communication queue) ==========
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # Port AMQP (Celery)
      - "15672:15672" # Interface de gestion (optionnel)
    networks:
      - microservices-network
    restart: unless-stopped
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - USERS_SERVICE_URL=http://users-service:8000
      - NOTIFICATION_SERVICE_URL=http://notification-service:8000
      - CONTACT_SERVICE_URL=http://contact-service:8000
    depends_on:
      - users-service
      - contact-service
    networks:
      - microservices-network
    restart: unless-stopped

  users-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile

    environment:
      - SERVICE_PORT=8000
      - DATABASE_URL=sqlite:///users_db.sqlite
    networks:
      - microservices-network
    restart: unless-stopped

 # ========== NOTIFICATION SERVICE (avec Celery) ==========
  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile

    environment:
      - SERVICE_PORT=8000
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672//
      # - DATABASE_URL=sqlite:///notification_db.sqlite
    depends_on:
      - rabbitmq
    networks:
      - microservices-network
    restart: unless-stopped
    # Lance le serveur + le worker Celery
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000 &
             celery -A config worker --loglevel=info -Q notifications "

  contact-service:
    build:
      context: ./contact-service
      dockerfile: Dockerfile

    environment:
      - SERVICE_PORT=8000
      - DATABASE_URL=sqlite:///contact_db.sqlite
      - NOTIFICATION_SERVICE_URL=http://notification-service:8000
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - notification-service
      - rabbitmq
    networks:
      - microservices-network
    restart: unless-stopped
     # Lance le serveur + le worker Celery
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000 &
        # celery -A config worker
        #         --loglevel=info
        #         --without-gossip
        #         --without-mingle
        #         --without-heartbeat
      "

networks:
  microservices-network:
    driver: bridge
