name: Lint - Code Quality

on:
  push:
    branches: 
    - '**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    # ✅ Optionnel : si tu veux tester plusieurs versions
    # strategy:
    #   matrix:
    #     python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
        
    - name: Install flake8 and pylint
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-django 
        
      # pylint pylint-django
        
      # ============================================
      #  LINT avec flake8
      # ============================================
      
    - name: Lint API Gateway
      run: |
        cd api-gateway
        flake8 . --count --max-complexity=10 --statistics --show-source
      
    - name: Lint User Service
      run: |
        cd user-service
        flake8 . --count --max-complexity=10 --statistics --show-source
      
    - name: Lint Contact Service
      run: |
        cd contact-service
        flake8 . --count --max-complexity=10 --statistics --show-source
      
    - name: Lint Notification Service
      run: |
        cd notification-service
        flake8 . --count --max-complexity=10 --statistics --show-source
      
      # ============================================
      #  LINT avec pylint (optionnel)
      # ============================================
      
    # - name: Pylint API Gateway
    #   run: |
    #    cd api-gateway
    #    pylint --load-plugins=pylint_django **/*.py || true
      
    # - name: Pylint User Service
    #   run: |
    #     cd user-service
    #     pylint --load-plugins=pylint_django **/*.py || true
      
    # - name: Pylint Contact Service
    #   run: |
    #     cd contact-service
    #     pylint --load-plugins=pylint_django **/*.py || true
      
    # - name: Pylint Notification Service
    #   run: |
    #     cd notification-service
    #     pylint --load-plugins=pylint_django **/*.py || true
